language: java
install: git clone https://github.com/BREAD5940/Pantry-Logging
script: ./gradlew test --include-build "./Pantry-Logging"
deploy:
    skip_cleanup: true
    provider: script
    script: bash .gen_docs.sh
    on:
        branch: master
        condition: $(git log --format="%cn" -n 1) != "Travis CI User"
